### ISSUE TITLE
Compilation error - coqui/src/mean_field/qe/qe_interface.cpp usage of roundup(...) from slate/internal/util.hh

### ISSUE THREAD

**Issue by HugoStrand** [AbInitioQHub/coqui#41]
Dear CoQuí developers,

I am trying to build CoQuí (on tag v0.3.0) but get stuck in a compilation error on some internal function in slate using slate/master on commit ded15290 (basically v2025.05.28). (I am on mac osx using gcc15, openmpi.) Here is the error message,

```
[ 71%] Building CXX object src/mean_field/CMakeFiles/meanfield.dir/qe/qe_interface.cpp.o
In file included from /opt/local/libexec/boost/1.81/include/boost/interprocess/detail/workaround.hpp:145,
                 from /opt/local/libexec/boost/1.81/include/boost/interprocess/allocators/allocator.hpp:23,
                 from /Users/xx/dev/coqui/extern/mpi_wrapper/mpi3/shared_window.hpp:11,
                 from /Users/xx/dev/coqui/src/numerics/shared_array/nda.hpp:27,
                 from /Users/xx/dev/coqui/src/utilities/symmetry.hpp:32,
                 from /Users/xx/dev/coqui/src/mean_field/symmetry/bz_symmetry.hpp:35,
                 from /Users/xx/dev/coqui/src/mean_field/qe/qe_system.hpp:36,
                 from /Users/xx/dev/coqui/src/mean_field/qe/qe_interface.cpp:30:
/Users/xx/apps/slate/include/slate/internal/util.hh:116:45: error: expected ')' before 'x'
  116 | inline constexpr std::common_type_t<T1, T2> roundup( T1 x, T2 y )
      |                                             ^~~~~~~
/Users/xx/apps/slate/include/slate/internal/util.hh:116:45: note: to match this '('
  116 | inline constexpr std::common_type_t<T1, T2> roundup( T1 x, T2 y )
      |                                             ^~~~~~~
/Users/xx/apps/slate/include/slate/internal/util.hh:116:45: error: expected ')' before 'x'
  116 | inline constexpr std::common_type_t<T1, T2> roundup( T1 x, T2 y )
      |                                             ^~~~~~~
/Users/xx/apps/slate/include/slate/internal/util.hh:116:45: note: to match this '('
  116 | inline constexpr std::common_type_t<T1, T2> roundup( T1 x, T2 y )
      |                                             ^~~~~~~
/Users/xx/apps/slate/include/slate/internal/util.hh:116:45: error: expected ')' before 'x'
  116 | inline constexpr std::common_type_t<T1, T2> roundup( T1 x, T2 y )
      |                                             ^~~~~~~
/Users/xx/apps/slate/include/slate/internal/util.hh:116:45: note: to match this '('
  116 | inline constexpr std::common_type_t<T1, T2> roundup( T1 x, T2 y )
      |                                             ^~~~~~~
/Users/xx/apps/slate/include/slate/internal/util.hh:116:45: error: expected ')' before 'x'
  116 | inline constexpr std::common_type_t<T1, T2> roundup( T1 x, T2 y )
      |                                             ^~~~~~~
/Users/xx/apps/slate/include/slate/internal/util.hh:116:45: note: to match this '('
  116 | inline constexpr std::common_type_t<T1, T2> roundup( T1 x, T2 y )
      |                                             ^~~~~~~
make[2]: *** [src/mean_field/CMakeFiles/meanfield.dir/qe/qe_interface.cpp.o] Error 1
make[1]: *** [src/mean_field/CMakeFiles/meanfield.dir/all] Error 2
make: *** [all] Error 2
```

Is this a know issue? Is there a particular version/tag of Slate that is supported by CoQuí?

Cheers, Hugo

**Comment by cnyeh** [comment]
Hi @HugoStrand , 

Thank you for reporting this bug. 

CoQuí should work with the latest SLATE: [v2025.05.28](https://github.com/icl-utk-edu/slate/releases/tag/v2025.05.28). 

I believe the error is coming from the conflict between SLATE `roundup` function and the operating system macro `round(x, y)`.  Depending on the operating system, the `roundup(x, y)` macro might get included indirectly by other dependencies of CoQui, e.g. hdf5, mpi, which will then trigger the compilation error you observed. See [here](https://github.com/icl-utk-edu/slate/issues/227). 

The issue is probably operating-system dependent, and I have not seen this issue on my linux system yet. 

I have added a simple workaround to avoid the macro conflict in PR #42.  Could you help confirm whether this resolves your issue or not?

**Comment by HugoStrand** [comment]
Dear @cnyeh, 

Thank you for the rapid response and the fix in PR #42! I can confirm that it fixes the compilation error. 👍 🥇 

Cheers, Hugo
